---
- name: ensure the keystone database is configured
  ini_file:
    dest: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ database_url }}"
  notify:
    - restart apache2
    - sync keystone database

- name: ensure keystone caching is configured
  ini_file:
    dest: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: memcache
      option: servers
      value: "{{ memcached_host }}"
  notify:
    - restart apache2

- name: ensure the fernet token provider is configured
  ini_file:
    dest: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: token
      option: provider
      value: fernet
  notify:
    - restart apache2
    - sync keystone database
