---
- name: check to see if the demo user exists in keystone
  command: "openstack user show --domain default demo"
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ openstack_admin_password }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_IDENTITY_API_VERSION: 3
  register: keystone_demo_user
  failed_when: keystone_demo_user.rc > 1
  changed_when: False

- name: ensure the demo user exists in keystone
  command: "openstack user create --domain default --password {{ openstack_demo_password }} demo"
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ openstack_admin_password }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_IDENTITY_API_VERSION: 3
  when: keystone_demo_user.rc != 0
