---
- name: check to see if the admin user exists in keystone
  command: "openstack user show --domain default admin"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  register: keystone_admin_user
  failed_when: keystone_admin_user.rc > 1
  changed_when: False

- name: ensure the admin user exists in keystone
  command: "openstack user create --domain default --password {{ openstack_admin_password }} admin"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  when: keystone_admin_user.rc != 0

- name: check to see if the demo user exists in keystone
  command: "openstack user show --domain default demo"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  register: keystone_demo_user
  failed_when: keystone_demo_user.rc > 1
  changed_when: False

- name: ensure the demo user exists in keystone
  command: "openstack user create --domain default --password {{ openstack_demo_password }} demo"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  when: keystone_demo_user.rc != 0
