---
- name: check to see if the demo user has the user role in keystone
  shell: "openstack role assignment list --project demo --user demo | wc -l"
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ openstack_admin_password }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_IDENTITY_API_VERSION: 3
  register: keystone_demo_user_user_role
  failed_when: keystone_demo_user_user_role.rc != 0
  changed_when: False

- name: ensure the demo user has the user role in keystone
  command: "openstack role add --project demo --user demo user"
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ openstack_admin_password }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_IDENTITY_API_VERSION: 3
  when: keystone_demo_user_user_role.stdout == '1'
