---
- name: set the hostname
  hostname:
    name: "{{ hostname | default(inventory_hostname) }}"
  tags: hostname

- name: make the hostname persistent
  copy:
    content: "{{ hostname | default(inventory_hostname) }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0645
  tags: hostname
