---
- name: set the hostname
  hostname:
    name: "{{ hostname | default(inventory_hostname) }}"
  tags: hostname

- name: make the hostname persistent
  copy:
    content: "{{ hostname | default(inventory_hostname) }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0645
  tags: hostname

- name: ensure the stupid "localhost" doesn't exist
  lineinfile:
    regexp: '^127\.0\.1\.1'
    state: absent
    dest: /etc/hosts
  tags: hostname
