---
- hosts: controller
  become: yes
  become_user: root
  roles:
    - role: hostname
    - role: ntp
    - role: openstack-keystone
      admin_password: "{{ admin_user_password }}"
      demo_password: "{{ demo_user_password }}"
      memcached_host: "{{ groups['memcached'][0] }}"
      service_password: "{{ keystone_password }}"
      database_host: "{{ groups['database'][0] }}"
      database_password: "{{ keystone_mysql_password }}"
    - role: openstack-glance
      admin_password: "{{ admin_user_password }}"
      memcached_host: "{{ groups['memcached'][0] }}:11211"
      database_host: "{{ groups['database'][0] }}"
      database_password: "{{ glance_mysql_password }}"
      keystone_hostname: "{{ groups['controller'][0] }}"
      service_password: "{{ glance_password }}"
    - role: openstack-nova
      admin_password: "{{ admin_user_password }}"
      memcached_host: "{{ groups['memcached'][0] }}:11211"
      database_host: "{{ groups['database'][0] }}"
      database_password: "{{ nova_mysql_password }}"
      keystone_hostname: "{{ groups['controller'][0] }}"
      glance_hostname: "{{ groups['controller'][0] }}"
      service_password: "{{ nova_password }}"
      # service_password: "blargh"
      # openstack_nova_management_ip: "{{ ipv4_address }}"
      # openstack_nova_hostname: "{{ groups['controller'][0] }}"
      # openstack_neutron_hostname: "{{ groups['controller'][0] }}"
      rabbitmq_hostname: "{{ groups['messaging'][0] }}"
      rabbitmq_username: "openstack"
      rabbitmq_password: "{{ rabbitmq_openstack_password }}"
