---
- hosts: controller
  become: yes
  become_user: root
  roles:
    - role: hostname
    - role: ntp
    - role: openstack-keystone
      admin_password: "{{ admin_user_password }}"
      demo_password: "{{ demo_user_password }}"
      memcached_host: "{{ groups['memcached'][0] }}"
      service_password: "{{ keystone_password }}"
      database_host: "{{ groups['database'][0] }}"
      database_password: "{{ keystone_mysql_password }}"
    - role: openstack-glance
      admin_password: "{{ admin_user_password }}"
      memcached_host: "{{ groups['memcached'][0] }}:11211"
      database_host: "{{ groups['database'][0] }}"
      database_password: "{{ glance_mysql_password }}"
      keystone_hostname: "{{ groups['controller'][0] }}"
      service_password: "{{ glance_password }}"
    # - role: openstack-nova
    #   openstack_nova_database_name: "nova"
    #   openstack_nova_database_url: "mysql+pymysql://{{ openstack_nova_database_username }}:{{ openstack_nova_database_password }}@{{ /{{ mysql_nova_database }}"
    #   openstack_nova_api_database_url: "mysql+pymysql://{{ mysql_nova_username }}:{{ mysql_nova_password }}@localhost/{{ mysql_nova_api_database }}"
    #   openstack_nova_management_ip: "{{ ipv4_address }}"
    #   openstack_nova_hostname: "{{ groups['controller'][0] }}"
    #   openstack_neutron_hostname: "{{ groups['controller'][0] }}"
    #   rabbitmq_hostname: localhost
    #   rabbitmq_username: "{{ rabbitmq_openstack_username }}"
    #   rabbitmq_password: "{{ rabbitmq_openstack_password }}"
