---
- hosts: all:!ntp_servers
  become: yes
  become_user: root
  roles:
    - role: openstack-keystone
      openstack_keystone_database_url: "mysql+pymysql://{{ mysql_keystone_username }}:{{ mysql_keystone_password }}@localhost/{{ mysql_keystone_database }}"
      openstack_keystone_hostname: "{{ groups['controller'][0] }}"
      openstack_keystone_memcache_servers: localhost:11211
