---
- hosts: all:!ntp_servers
  become: yes
  become_user: root
  roles:
    - role: openstack-keystone
      openstack_keystone_database_url: "mysql+pymysql://{{ mysql_keystone_username }}:{{ mysql_keystone_password }}@localhost/{{ mysql_keystone_database }}"
      openstack_keystone_hostname: "{{ groups['controller'][0] }}"
      openstack_keystone_memcache_servers: localhost:11211
    - role: openstack-glance
      openstack_glance_database_url: "mysql+pymysql://{{ mysql_glance_username }}:{{ mysql_glance_password }}@localhost/{{ mysql_glance_database }}"
      openstack_glance_hostname: "{{ groups['controller'][0] }}"
    - role: openstack-nova
      openstack_nova_database_url: "mysql+pymysql://{{ mysql_nova_username }}:{{ mysql_nova_password }}@localhost/{{ mysql_nova_database }}"
      openstack_nova_api_database_url: "mysql+pymysql://{{ mysql_nova_username }}:{{ mysql_nova_password }}@localhost/{{ mysql_nova_api_database }}"
      openstack_nova_management_ip: "{{ ipv4_address }}"
      openstack_nova_hostname: "{{ groups['controller'][0] }}"
      openstack_neutron_hostname: "{{ groups['controller'][0] }}"
      rabbitmq_hostname: localhost
      rabbitmq_username: "{{ rabbitmq_openstack_username }}"
      rabbitmq_password: "{{ rabbitmq_openstack_password }}"
    - role: openstack-neutron
      openstack_neutron_database_url: "mysql+pymysql://{{ mysql_neutron_username }}:{{ mysql_neutron_password }}@localhost/{{ mysql_neutron_database }}"
      openstack_neutron_hostname: "{{ inventory_hostname }}"
      openstack_keystone_hostname: "{{ groups['controller'][0] }}"
      openstack_nova_hostname: "{{ groups['controller'][0] }}"
      rabbitmq_hostname: localhost
      rabbitmq_username: "{{ rabbitmq_openstack_username }}"
      rabbitmq_password: "{{ rabbitmq_openstack_password }}"
      openstack_neutron_local_ip: "{{ ipv4_address }}"
      openstack_neutron_ext_interface: "{{ interface }}"
    - role: openstack-horizon
      openstack_keystone_hostname: "{{ groups['controller'][0] }}"
