---
- name: ensure the ubuntu cloud keyring is installed
  apt:
    name: ubuntu-cloud-keyring
    state: present

- name: ensure the cloudarchive source is configured
  apt_repository:
    repo: "{{ cloudarchive_source }}"
    state: present
    update_cache: yes

- name: ensure the OpenStack client is installed
  apt:
    name: python-openstackclient
    state: present

- name: ensure the openstack rabbitmq user is present
  rabbitmq_user:
    user: "{{ openstack_rabbitmq_username }}"
    password: "{{ openstack_rabbitmq_password }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
  tags: rabbitmq
