- name: restart glance-api
  service:
    name: glance-api
    state: restarted

- name: restart glance-registry
  service:
    name: glance-registry
    state: restarted

- name: sync glance database
  command: glance-manage db_sync
  become: yes
  become_user: keystone

