---
- name: sync neutron database
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  become: yes
  become_user: neutron

- name: restart nova-api
  service:
    name: nova-api
    state: restarted

- name: restart neutron-dhcp-agent
  service:
    name: neutron-dhcp-agent
    state: restarted

- name: restart neutron-linuxbridge-agent
  service:
    name: neutron-linuxbridge-agent
    state: restarted

- name: restart neutron-l3-agent
  service:
    name: neutron-l3-agent
    state: restarted

- name: restart neutron-metadata-agent
  service:
    name: neutron-metadata-agent
    state: restarted

- name: restart neutron-openvswitch-agent
  service:
    name: neutron-openvswitch-agent
    state: restarted

- name: restart neutron-server
  service:
    name: neutron-server
    state: restarted
