---
- name: ensure neutron is configured
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ database_url }}"
    - section: DEFAULT
      option: transport_url
      value: "{{ rabbitmq_url }}"
    - section: DEFAULT
      option: allow_overlapping_ips
      value: True
    - section: DEFAULT
      option: auth_strategy
      value: keystone
    - section: DEFAULT
      option: core_plugin
      value: ml2
    - section: DEFAULT
      option: notify_nova_on_port_data_changes
      value: True
    - section: DEFAULT
      option: notify_nova_on_port_status_changes
      value: True
    # - section: DEFAULT
    #   option: rpc_backend
    #   value: rabbit
    - section: DEFAULT
      option: service_plugins
      value: router
    # - section: DEFAULT
    #   option: api_workers
    #   value: 2
    - section: keystone_authtoken
      option: auth_uri
      value: "http://{{ keystone_hostname }}:5000"
    - section: keystone_authtoken
      option: auth_url
      value: "http://{{ keystone_hostname }}:35357"
    - section: keystone_authtoken
      option: memcached_servers
      value: "{{ memcached_host }}"
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: project_domain_name
      value: Default
    - section: keystone_authtoken
      option: user_domain_name
      value: Default
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: username
      value: "{{ service_username }}"
    - section: keystone_authtoken
      option: password
      value: "{{ service_password }}"
    - section: nova
      option: auth_url
      value: "http://{{ keystone_hostname }}:35357"
    - section: nova
      option: auth_type
      value: password
    - section: nova
      option: password
      value: "{{ nova_password }}"
    - section: nova
      option: project_domain_name
      value: Default
    - section: nova
      option: project_name
      value: service
    - section: nova
      option: region_name
      value: RegionOne
    - section: nova
      option: user_domain_name
      value: Default
    - section: nova
      option: username
      value: "{{ nova_username }}"
    # - section: oslo_messaging_rabbit
    #   option: rabbit_host
    #   value: "{{ rabbitmq_hostname }}"
    # - section: oslo_messaging_rabbit
    #   option: rabbit_userid
    #   value: "{{ rabbitmq_username }}"
    # - section: oslo_messaging_rabbit
    #   option: rabbit_password
    #   value: "{{ rabbitmq_password }}"
  notify:
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart neutron-openvswitch-agent
  tags: neutron

- name: ensure neutron ml2 plugin is configured
  ini_file:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: ml2
      option: extension_drivers
      value: port_security
    - section: ml2
      option: mechanism_drivers
      value: openvswitch,l2population
    - section: ml2
      option: tenant_network_types
      value: gre
    - section: ml2
      option: type_drivers
      value: "flat,vlan,gre,vxlan"
    - section: ml2_type_flat
      option: flat_networks
      value: external
    - section: ml2_type_gre
      option: tunnel_id_ranges
      value: 1:1000
    - section: ml2_type_vlan
      option: network_vlan_ranges
      value: external,vlan:1:1000
    - section: ml2_type_vxlan
      option: vni_ranges
      value: 1:1000
    - section: securitygroup
      option: enable_ipset
      value: True
    - section: securitygroup
      option: firewall_driver
      value: neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
  notify:
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart neutron-openvswitch-agent
  tags: neutron

- name: ensure neutron linux bridge agent is configured
  ini_file:
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: linux_bridge
      option: physical_interface_mappings
      value: provider:br-ex
    - section: securitygroup
      option: enable_security_group
      value: True
    - section: securitygroup
      option: firewall_driver
      value: neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
    - section: vxlan
      option: enable_vxlan
      value: True
    - section: vxlan
      option: l2_population
      value: True
    - section: vxlan
      option: local_ip
      value: "{{ ipv4_address }}"
  notify:
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart neutron-openvswitch-agent
  tags: neutron

- name: ensure neutron layer-3 agent is configured
  ini_file:
    dest: /etc/neutron/l3_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: DEFAULT
      option: external_network_bridge
      value:
    - section: DEFAULT
      option: interface_driver
      value: neutron.agent.linux.interface.OVSInterfaceDriver
  notify:
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart neutron-openvswitch-agent
  tags: neutron

- name: ensure neutron dhcp agent is configured
  ini_file:
    dest: /etc/neutron/dhcp_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: DEFAULT
      option: dhcp_driver
      value: neutron.agent.linux.dhcp.Dnsmasq
    - section: DEFAULT
      option: enable_isolated_metadata
      value: True
    - section: DEFAULT
      option: interface_driver
      value: neutron.agent.linux.interface.OVSInterfaceDriver
  notify:
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart neutron-openvswitch-agent
  tags: neutron

- name: ensure neutron metadata agent is configured
  ini_file:
    dest: /etc/neutron/metadata_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: DEFAULT
      option: nova_metadata_ip
      value: "{{ ansible_hostname }}"
    - section: DEFAULT
      option: metadata_proxy_shared_secret
      value: "{{ proxy_shared_secret }}"
    - section: DEFAULT
      option: metadata_workers
      value: 2
  notify:
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart neutron-openvswitch-agent
  tags: neutron

- name: ensure neutron metadata agent is configured
  ini_file:
    dest: /etc/neutron/metadata_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: DEFAULT
      option: nova_metadata_ip
      value: "{{ ansible_hostname }}"
    - section: DEFAULT
      option: metadata_proxy_shared_secret
      value: "{{ proxy_shared_secret }}"
  notify:
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart neutron-openvswitch-agent
  changed_when: True
  tags: neutron

- name: ensure openvswitch agent is configured
  ini_file:
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: agent
      option: tunnel_types
      value: gre,vxlan
    - section: agent
      option: l2_population
      value: True
    - section: ovs
      option: bridge_mappings
      value: external:br-ex
    - section: ovs
      option: local_ip
      value: "{{ ansible_default_ipv4.address }}"
    - section: securitygroup
      option: firewall_driver
      value: neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
  changed_when: True
  notify:
    - sync neutron database
    - restart neutron-server
    - restart neutron-linuxbridge-agent
    - restart neutron-dhcp-agent
    - restart neutron-metadata-agent
    - restart neutron-l3-agent
    - restart neutron-openvswitch-agent
  tags: neutron

- name: ensure nova is configured for neutron
  ini_file:
    dest: /etc/nova/nova.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: neutron
      option: url
      value: "http://{{ ansible_hostname }}:9696"
    - section: neutron
      option: auth_url
      value: "http://{{ keystone_hostname }}:35357"
    - section: neutron
      option: auth_type
      value: password
    - section: neutron
      option: project_domain_name
      value: Default
    - section: neutron
      option: user_domain_name
      value: Default
    - section: neutron
      option: region_name
      value: RegionOne
    - section: neutron
      option: project_name
      value: service
    - section: neutron
      option: username
      value: "{{ service_username }}"
    - section: neutron
      option: password
      value: "{{ service_password }}"
    # - section: neutron
    #   option: metadata_proxy_shared_secret
    #   value: "{{ proxy_shared_secret }}"
    # - section: neutron
    #   option: service_metadata_proxy
    #   value: True
  notify:
    - restart nova-api
  tags: neutron,nova
