---
- name: ensure mysql is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - python-mysqldb

- name: ensure mysql is running
  service:
    name: mysql
    state: started

- name: update mysql root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: create .my.cnf file with root password credentials
  template:
    src: root/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: delete anonymous mysql user for {{ ansible_hostname }}
  mysql_user:
    user: ""
    state: absent

- name: delete anonymous mysql user for localhost
  mysql_user:
    user: ""
    state: absent

- name: remove the test database
  mysql_db:
    db: test
    state: absent

- name: create required mysql databases
  mysql_db:
    db: "{{ item }}"
    state: present
  with_items: "{{ mysql_databases }}"

- name: create required mysql users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host }}"
    priv: "{{ item.priv }}"
  with_items: "{{ mysql_users }}"

- name: ensure mysql is configured properly for openstack
  template:
    src: etc/mysql/conf.d/mysqld_openstack.cnf.j2
    dest: /etc/mysql/conf.d/mysqld_openstack.cnf
  notify: restart mysql
