---
- name: ensure nova is configured
  ini_file:
    dest: /etc/nova/nova.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: DEFAULT
      option: transport_url
      value: "{{ rabbitmq_url }}"
    # - section: DEFAULT
    #   option: enabled_apis
    #   value: "osapi_compute,metadata"
    # - section: DEFAULT
    #   option: osapi_compute_workers
    #   value: 2
    # - section: DEFAULT
    #   option: metadata_workers
    #   value: 2
    # - section: DEFAULT
    #   option: rpc_backend
    #   value: rabbit
    - section: DEFAULT
      option: auth_strategy
      value: keystone
    - section: DEFAULT
      option: my_ip
      value: "{{ ansible_default_ipv4.address }}"
    - section: DEFAULT
      option: use_neutron
      value: True
    - section: DEFAULT
      option: firewall_driver
      value: nova.virt.firewall.NoopFirewallDriver
    # - section: DEFAULT
    #   option: logdir
    #   value:
    - section: api_database
      option: connection
      value: "{{ api_database_url }}"
    - section: database
      option: connection
      value: "{{ database_url }}"
    - section: glance
      option: api_servers
      value: "http://{{ glance_hostname }}:9292"
    - section: keystone_authtoken
      option: auth_uri
      value: "http://{{ keystone_hostname }}:5000"
    - section: keystone_authtoken
      option: auth_url
      value: "http://{{ keystone_hostname }}:35357"
    - section: keystone_authtoken
      option: memcached_servers
      value: "{{ memcached_host }}"
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: project_domain_name
      value: Default
    - section: keystone_authtoken
      option: user_domain_name
      value: Default
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: username
      value: "{{ service_username }}"
    - section: keystone_authtoken
      option: password
      value: "{{ service_password }}"
    # - section: libvirt
    #   option: images_type
    #   value: lvm
    # - section: libvirt
    #   option: images_volume_group
    #   value: nova-volumes
    - section: oslo_concurrency
      option: lock_path
      value: "/var/lib/nova/tmp"
    # - section: oslo_messaging_rabbit
    #   option: rabbit_host
    #   value: "{{ rabbitmq_hostname }}"
    # - section: oslo_messaging_rabbit
    #   option: rabbit_userid
    #   value: "{{ rabbitmq_username }}"
    # - section: oslo_messaging_rabbit
    #   option: rabbit_password
    #   value: "{{ rabbitmq_password }}"
    - section: vnc
      option: enabled
      value: True
    - section: vnc
      option: vncserver_listen
      value: 0.0.0.0
    - section: vnc
      option: vncserver_proxyclient_address
      value: $my_ip
    - section: vnc
      option: novncproxy_base_url
      value: "http://{{ ansible_hostname }}:6080/vnc_auto.html"
    # - section: conductor
    #   option: workers
    #   value: 2
  notify:
    - sync nova database
    - sync nova-api database
    - restart nova-api
    - restart nova-compute
    - restart nova-consoleauth
    - restart nova-scheduler
    - restart nova-conductor
    - restart nova-novncproxy
  tags: nova
