---
- name: ensure horizon is configured
  template:
    src: etc/openstack-dashboard/local_settings.py.j2
    dest: /etc/openstack-dashboard/local_settings.py
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache2

