---
- name: ensure the horizon packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-dashboard

- name: ensure the ubuntu theme is uninstalled
  apt:
    name: openstack-dashboard-ubuntu-theme
    state: absent
    purge: yes
  notify: restart apache2

- include: configuration.yml

- meta: flush_handlers
