---
admin_password: CHANGEME
demo_password: CHANGEME

memcached_host: localhost:11211

service_name: keystone
service_description: OpenStack Identity

log_dir: /var/log/keystone

database_name: keystone
database_username: keystone
database_host: localhost
database_password: CHANGEME


