---
openstack_nova_username: nova
openstack_nova_password: iamnotverysecret
openstack_nova_service_name: nova
openstack_nova_service_description: Openstack Compute
openstack_nova_hostname: localhost
openstack_glance_hostname: localhost
openstack_neutron_hostname: localhost
openstack_neutron_username: neutron
openstack_neutron_password: iamnotverysecret
openstack_keystone_hostname: localhost
openstack_metadata_proxy_shared_secret: ch33t0srg00d
openstack_nova_management_ip: 127.0.0.1
openstack_nova_novncproxy_host: localhost
openstack_nova_novncproxy_port: 6080
openstack_nova_database_url: sqlite:////var/lib/nova/nova.db
openstack_nova_proxyclient_ip: "{{ openstack_nova_management_ip }}"
