- name: ensure glance api is configured
  ini_file:
    dest: /etc/glance/glance-api.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ database_url }}"
    - section: keystone_authtoken
      option: auth_uri
      value: "http://{{ keystone_hostname }}:5000"
    - section: keystone_authtoken
      option: auth_url
      value: "http://{{ keystone_hostname }}:35357"
    - section: keystone_authtoken
      option: memcached_servers
      value: "{{ memcached_host }}"
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: project_domain_name
      value: Default
    - section: keystone_authtoken
      option: user_domain_name
      value: Default
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: username
      value: "{{ service_username }}"
    - section: keystone_authtoken
      option: password
      value: "{{ service_password }}"
    - section: paste_deploy
      option: flavor
      value: keystone
    - section: glance_store
      option: stores
      value: "file,http"
    - section: glance_store
      option: default_store
      value: file
    - section: glance_store
      option: filesystem_store_datadir
      value: "{{ image_path }}"
  notify:
    - restart glance-api
    - sync glance database
  tags: glance,mysql

- name: ensure glance registry is configured
  ini_file:
    dest: /etc/glance/glance-registry.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ database_url }}"
    - section: keystone_authtoken
      option: auth_uri
      value: "http://{{ keystone_hostname }}:5000"
    - section: keystone_authtoken
      option: auth_url
      value: "http://{{ keystone_hostname }}:35357"
    - section: keystone_authtoken
      option: memcached_servers
      value: "{{ memcached_host }}"
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: project_domain_name
      value: default
    - section: keystone_authtoken
      option: user_domain_name
      value: default
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: username
      value: "{{ service_username }}"
    - section: keystone_authtoken
      option: password
      value: "{{ service_password }}"
    - section: paste_deploy
      option: flavor
      value: keystone
  notify:
    - restart glance-registry
  tags: glance
