---
- name: ensure the glance endpoints exist in keystone
  keystone_endpoint:
    url: "{{ item.url }}"
    interface: "{{ item.interface }}"
    service: "{{ openstack_glance_service_name }}"
    auth_username: admin
    auth_password: "{{ openstack_admin_password }}"
    auth_url: "http://{{ openstack_keystone_hostname }}:35357/v3"
  with_items:
    - interface: admin
      url: "http://{{ openstack_glance_hostname }}:9292"
    - interface: internal
      url: "http://{{ openstack_glance_hostname }}:9292"
    - interface: public
      url: "http://{{ openstack_glance_hostname }}:9292"
  tags: glance, keystone
