---
- name: check to see if the cinder service exists in keystone
  command: "openstack service show {{ openstack_cinder_service_name }}"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  register: cinder_service
  failed_when: cinder_service.rc > 1
  changed_when: False

- debug:
    msg: "cinder_service: {{ cinder_service }}"

- name: ensure the cinder service exists in keystone
  command: "openstack service create --name {{ openstack_cinder_service_name }} --description '{{ openstack_cinder_service_description }}' volume"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  when: cinder_service.rc != 0

- name: check to see if the cinderv2 service exists in keystone
  command: "openstack service show {{ openstack_cinderv2_service_name }}"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  register: cinderv2_service
  failed_when: cinderv2_service.rc > 1
  changed_when: False

- name: ensure the cinderv2 service exists in keystone
  command: "openstack service create --name {{ openstack_cinderv2_service_name }} --description '{{ openstack_cinder_service_description }}' volumev2"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  when: cinderv2_service.rc != 0
