---
- name: check to see if the cinder user exists in keystone
  command: "openstack user show --domain default cinder"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  register: keystone_cinder_user
  failed_when: keystone_cinder_user.rc > 1
  changed_when: False

- name: ensure the cinder user exists in keystone
  command: "openstack user create --domain default --password {{ openstack_cinder_password }} cinder"
  environment:
    OS_TOKEN: "{{ openstack_keystone_admin_token }}"
    OS_IDENTITY_API_VERSION: 3
    OS_URL: "http://{{ openstack_keystone_hostname }}:35357/v3"
    OS_USERNAME: "keystone"
  when: keystone_cinder_user.rc != 0
